// Foreground literals from the attributed 25 palette assets. Rendering, not
// static identifier counts, must agree with both declared appearances.
export const PALETTES = [
  { name: "aura", dark: "#edecee", light: "#edecee" },
  { name: "ayu", dark: "#BFBDB6", light: "#BFBDB6" },
  { name: "carbonfox", dark: "#f2f4f8", light: "#161616" },
  { name: "catppuccin", dark: "#cdd6f4", light: "#4c4f69" },
  { name: "catppuccin-frappe", dark: "#c6d0f5", light: "#c6d0f5" },
  { name: "catppuccin-macchiato", dark: "#cad3f5", light: "#cad3f5" },
  { name: "cobalt2", dark: "#ffffff", light: "#193549" },
  { name: "dracula", dark: "#f8f8f2", light: "#282a36" },
  { name: "everforest", dark: "#d3c6aa", light: "#5c6a72" },
  { name: "flexoki", dark: "#CECDC3", light: "#100F0F" },
  { name: "gruvbox", dark: "#ebdbb2", light: "#3c3836" },
  { name: "kanagawa", dark: "#DCD7BA", light: "#54433A" },
  { name: "matrix", dark: "#62ff94", light: "#203022" },
  { name: "mercury", dark: "#dddde5", light: "#363644" },
  { name: "nightowl", dark: "#d6deeb", light: "#d6deeb" },
  { name: "nord", dark: "#ECEFF4", light: "#2E3440" },
  { name: "one-dark", dark: "#abb2bf", light: "#383a42" },
  { name: "osaka-jade", dark: "#C1C497", light: "#111c18" },
  { name: "palenight", dark: "#a6accd", light: "#292d3e" },
  { name: "rosepine", dark: "#e0def4", light: "#575279" },
  { name: "solarized", dark: "#839496", light: "#657b83" },
  { name: "synthwave84", dark: "#ffffff", light: "#262335" },
  { name: "tokyonight", dark: "#c8d3f5", light: "#3760bf" },
  { name: "vesper", dark: "#FFFFFF", light: "#101010" },
  { name: "zenburn", dark: "#dcdccc", light: "#3f3f3f" },
];
